<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
    <title>Sybil Shane Studio &#8212; Development</title>
    <meta name="title" content="Sybil Shane Studio" />
    <meta name="publisher" content="Sybil Shane Studio" />
    <meta name="author" content="Sybil Shane Studio" />
    <meta name="description" content="Sybil Shane Studio" />
    <meta name="keywords" content="Sybil Shane Studio, Sybil Shane, postcards, calligraphy, asian art, greeting cards, art prints, teeshirts, totes, art nouveau, gifts, contemporary art, art deco" />
    <meta name="copyright" content="Sybil Shane Studio" />
    <meta name="HTMLauthor" content="digitopolis media corporation; updates: Barbara Miller" />
    <meta name="revisit-after" content="10 days" />
    <meta http-equiv="expires" content="Fri, 01 Jan 2002 07:20:55 GMT" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <meta name="robots" content="all" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="MSSmartTagsPreventParsing" content="true" />
    <meta http-equiv="imagetoolbar" content="no" />

    <script language="Javascript" type="text/javascript">
        <!--
        if (navigator.userAgent.toLowerCase().indexOf('webtv') > -1) {
         top.location.replace('upgrade.html');
        } else if (!document.getElementById) {
         top.location.replace('upgrade.html');
        }
        //-->
    </script>

    <script language="JavaScript" type="text/javascript" src="norightclick.js"></script>

    <script language="JavaScript" type="text/javascript" src="popup.js"></script>

    <script language="JavaScript" type="text/javascript">
    <!--
    /* pre-load images for menu */
    	var aboutus_over = new Image(62,22);
    	aboutus_over.src = "images/inside/nav_aboutus-over.gif";
    	
    	var gallery_over = new Image(49,22);
    	gallery_over.src = "images/inside/nav_gallery-over.gif";

    	var pricesheet_over = new Image(75,22);
    	pricesheet_over.src = "images/inside/nav_pricesheet-over.gif";

    	var products_over = new Image(64,22);
    	products_over.src = "images/inside/nav_products-over.gif";

    	var contactus_over = new Image(73,22);
    	contactus_over.src = "images/inside/nav_contactus-over.gif";

    	var home_over = new Image(43,22);
    	home_over.src = "images/inside/nav_home-over.gif";
    	
    	function MIout (sMI) {
    		document.getElementById(sMI).setAttribute("src","images/inside/nav_" + sMI + ".gif");
    	}

    	function MIover (sMI) {
    		document.getElementById(sMI).setAttribute("src","images/inside/nav_" + sMI + "-over.gif");
    	}
    //-->
    </script>

    <style type="text/css" media="screen">
        @import url(styles/type.css);
        @import url(styles/inside.css);
    </style>

</head>
