        <div id="imagebox">

            <img src="images/headers/img_products.jpg" width="200" height="202" alt="Bell" />

        </div>

        <div id="contentbox">

<h1>
<img src="images/title-products.gif" height="25" alt="Sybil Shane Studio &mdash; Products" />
</h1>

<ul id="menu">
  <li><a href="products.php?product=card">greeting cards</a></li>
  <li><a href="products.php?product=gift">gift prints</a></li>
  <li><a href="products.php?product=small">framed prints&mdash;small</a></li>
  <li><a href="products.php?product=large">framed prints&mdash;large</a></li>
  <li><a href="products.php?product=tee">tees</a></li>
  <li><a href="products.php?product=tote">tote bags</a></li>
  <li><a href="products.php?product=tile">tiles</a></li>
</ul>

        </div>
        <br clear="all" />
